### ISSUE TITLE
Do the append-dummy-data test

### ISSUE THREAD

**Issue by maho3** [maho3/ltu-ili#34]
Context: We are seeing that sbi is struggling to model posteriors given high-dimensional data, even when that high-d data is more informative. As an example, when you do inference using the density_field summaries, you get worse constraints than if you do TPCF, even though density_field should technically have the exact same information + some more (see [paper](https://arxiv.org/abs/2209.04310)). Here's a plot showing this,
![image (4)](https://user-images.githubusercontent.com/11132524/214018231-f1eb01e8-e4b3-4168-bfee-03fe95afe4cc.png)

Task: Perform a test in which we append dummy variables to a known summary (e.g. TPCF). The dummy variables should just be random noise, and not informative of cosmo parameters. The ILI models should then learn to ignore these dummy variables and produce the same posteriors with and without them. If not, then we have a problem!

**Comment by CompiledAtBirth** [comment]
Would a test with a fast PM code as the forward numerical solver (eg FastPM, COLA) within pyDELFI be relevant for instance?

**Comment by maho3** [comment]
Yes! For sure this is one of our priorities. We are working on adding simulation sampling in #37 and adding pyDELFI inference in #36 . Ultimately, we want to test training convergence with and without active learning.

This specific issue, however, is just to test how stable our inference is w.r.t. data dimensionality
