### ISSUE TITLE
Add a validation metric to just save samples

### ISSUE THREAD

**Issue by maho3** [maho3/ltu-ili#50]
Sometimes we want to just save samples from the posterior, so we can use them for downstream tasks (e.g. nested sampling) or making custom plots

**Comment by CompiledAtBirth** [comment]
Additional class :[PosteriorSamples(_SampleBasedMetric)](https://github.com/maho3/ltu-ili/blob/nico_50_56_71_73/ili/validation/metrics.py)

- x and theta can either be a test set or a single pair
