### ISSUE TITLE
Combine TARP and RankStatistics metrics

### ISSUE THREAD

**Issue by maho3** [maho3/ltu-ili#56]
Both the TARP and the PlotRankStatistics metrics require you to sample posteriors for all members of the test set. They are currently different classes, requiring you to resample the whole test set twice to calculate both. They should be merged, and the TARP metric should be calculated from the samples already produced in PlotRankStatistics. 

Also, add functionality to choose which rank statistics to plot. Maybe its prudent to change the joint metric to 'CheckPosteriorCoverage' or something.

**Comment by maho3** [comment]
Note, this will need to account for the pydelfi backend not supporting tarp

**Comment by CompiledAtBirth** [comment]
Additional class :[PosteriorCoverage(_SampleBasedMetric)](https://github.com/maho3/ltu-ili/blob/nico_50_56_71_73/ili/validation/metrics.py)

 - mus, stds, ranks are not longer lists to append but arrays when sampling  the posterior
 - "trues" seemed to be identical to theta (of the test set), is there a reason we create a copy?
 - I did a SNLE test without execution errors, but the plots for _toy_sbi_ are not good. Need to address issues 73 for more readability beforehand

**Comment by CompiledAtBirth** [comment]
(commit: 68cd48e6d8b11e0ca2414b542a2f0a449329e7cd)
