### ISSUE TITLE
Create MDN example for pydelfi with Quijote

### ISSUE THREAD

**Issue by DeaglanBartlett** [maho3/ltu-ili#58]
We have an example using MDN for Quijote with sbi ([examples/configs/infer/quijote_sbi_MDN.yaml](https://github.com/maho3/ltu-ili/blob/cd34ab28da7c1e73dc2305d42453373b4addccfe/examples/configs/infer/quijote_sbi_MDN.yaml)), but not yet for pydelfi. For symmetry between the two backends, we should have this for both

**Comment by maho3** [comment]
I think we may already have too many example configurations and the `examples` folder is getting crowded. We already have an example `pydelfi` MDN implementation in the `toy_pydelfi.py` example. It should be trivial for the users to extend the quijote one to MDN. Is that sufficient to close this issue?

**Comment by DeaglanBartlett** [comment]
I agree. I will close the issue now
