### ISSUE TITLE
Build a test suite for ltu-ili

### ISSUE THREAD

**Issue by DeaglanBartlett** [maho3/ltu-ili#68]
The functionality of ltu-ili is becoming too diverse to manually test everything for every PR. The idea of this project would be to write consolidated testing scripts to check that everything imports, builds, and runs correctly. These would check:

- Sbi and pydelfi backends (installation and running)
- SNPE vs SNLE vs SNRE models
- Single-round vs multiround inference
- Documentation building

**Comment by DeaglanBartlett** [comment]
Commit 9ec28108d5747e7d42b2061251fb4aa3f633de00 now includes multiround inference test by running [examples/toy_sbi_multiround.py](https://github.com/maho3/ltu-ili/blob/9ec28108d5747e7d42b2061251fb4aa3f633de00/examples/toy_sbi_multiround.py).

Remaining checks:
- SNPE vs SNLE vs SNRE models

**Comment by DeaglanBartlett** [comment]
PR #84 sets up the basis for automated pytest and build checks. The new features are

- Build checks of the sbi and pydelfi versions of the code
- Some simple tests which can be run with pytest and pytest-cov. These (so far) cover:
    - sbi SNPE
    - sbi SNLE
    - sbi multiround

The current code coverage is 58%, so this needs improving, but is a start. We need to think about how to add pydelfi tests into this setup given that this requires different python dependencies than sbi.

**Comment by maho3** [comment]
Thanks for making progress on the tests! Just so I'm following along correctly... Are we planning to use both the `run_tests.sh` and the things in `ltu-ili/tests`? Or is the `ltu-ili/tests` the final version, which can be run automatically with pytest?

**Comment by DeaglanBartlett** [comment]
No the script `run_tests.sh` was an old (bad) attempt to address this issue. I will remove this script before a PR, but am leaving it there for now so that I can check I've covered everything in `ltu-ili/tests` that I'd tried to cover in that script.

**Comment by DeaglanBartlett** [comment]
I've now added some `pydelfi` tests in commit 4b2600a2b7e4ae90f245d5e0e40ad430f19ac6ae. This commit also adds a script `tests/run.sh` which will eventually be replaced by an improved script in `.github/workflows`, but is convenient for now when running the tests locally. This script runs the `sbi` and `pydelfi` tests in different environments and then merges the results of the tests to produce a single coverage report. 

The state of the testing is now
```
Name                                Stmts   Miss  Cover   Missing
-----------------------------------------------------------------
ili/__init__.py                         8      2    75%   8-9
ili/dataloaders/__init__.py             1      0   100%
ili/dataloaders/loaders.py            100     21    79%   43, 53, 62, 130-145, 154, 162, 170, 185-187, 202-205, 257, 305, 313, 321
ili/embedding/__init__.py               1      0   100%
ili/embedding/fcn.py                   25     14    44%   26-30, 38-46, 57
ili/inference/__init__.py               5      0   100%
ili/inference/pydelfi_wrappers.py      51      0   100%
ili/inference/runner_pydelfi.py        47      0   100%
ili/inference/runner_sbi.py           136     19    86%   94, 100, 155-162, 192-198, 214, 225, 232-233, 250-253, 299
ili/utils/__init__.py                   1      0   100%
ili/utils/cosmology.py                 26      0   100%
ili/utils/import_utils.py               7      0   100%
ili/utils/samplers.py                  37      0   100%
ili/validation/__init__.py              2      0   100%
ili/validation/metrics.py             175     15    91%   71, 193-196, 215, 232, 243, 265, 274, 293, 357, 367-370, 387
ili/validation/runner.py               56      3    95%   70, 117-118
-----------------------------------------------------------------
TOTAL                                 678     74    89%
```
so we see that there are 74 lines of code still uncovered. Some general problems which cover a large fraction of the untested lines are:

- We currently don't test the `SummarizerDatasetLoader` class
- None of our test examples use any embedding, so `ili.embedding.fcn` is practically untested
- We do not use the `load_nets()` function for `runner_sbi.SBIRunner` for any case other than SNPE
- There is not a SNRE example for `sbi` yet

There are of course other things to add, but this should provide a good starting point for the next set of tests to prioritise.

**Comment by DeaglanBartlett** [comment]
The four points mentioned above have now been addressed, taking the code coverage to 95%:

```
Name                                Stmts   Miss  Cover   Missing
-----------------------------------------------------------------
ili/__init__.py                         8      2    75%   8-9
ili/dataloaders/__init__.py             1      0   100%
ili/dataloaders/loaders.py            100      7    93%   53, 62, 145, 257, 305, 313, 321
ili/embedding/__init__.py               1      0   100%
ili/embedding/fcn.py                   25      1    96%   57
ili/inference/__init__.py               5      0   100%
ili/inference/pydelfi_wrappers.py      51      0   100%
ili/inference/runner_pydelfi.py        47      0   100%
ili/inference/runner_sbi.py           136      4    97%   94, 100, 162, 299
ili/utils/__init__.py                   1      0   100%
ili/utils/cosmology.py                 26      0   100%
ili/utils/import_utils.py               7      0   100%
ili/utils/samplers.py                  37      0   100%
ili/validation/__init__.py              2      0   100%
ili/validation/metrics.py             175     15    91%   71, 193-196, 215, 232, 243, 265, 274, 293, 357, 367-370, 387
ili/validation/runner.py               56      3    95%   70, 117-118
-----------------------------------------------------------------
TOTAL                                 678     32    95%
```

The remaining steps for this issue are

- Wait for PR #83 to be accepted so that we can add tests for the new code here before considering merging to the main branch.
- Update the script in `.github/workflows` so that it mimics the behaviour of `tests/run.sh`
- Add tests to address the remaining 32 lines of code
