### ISSUE TITLE
Add customizable / automatic saving signatures for new models

### ISSUE THREAD

**Issue by maho3** [maho3/ltu-ili#73]
Currently, rerunning an inference pipeline will save data in the exact same spot as a previous run. This will overrun previous models, requiring the user to move the old version manually without rerunning. It would be nice if we had an easy-to-load configuration parameter which provided a name, prefix, or custom directory to our save files to prevent them from overwriting. By default, this could be automatically configured from the type of model training and the time of run.

**Comment by CompiledAtBirth** [comment]
I can be assigned to this and create a branch  while making the Figures for the draft slides before next Monday.
